<?php 
 $GLOBALS["dictionary"]["bill_Billables"]=array (
  'table' => 'bill_billables',
  'audited' => true,
  'inline_edit' => true,
  'duplicate_merge' => true,
  'fields' => 
  array (
    'id' => 
    array (
      'name' => 'id',
      'vname' => 'LBL_ID',
      'type' => 'id',
      'required' => true,
      'reportable' => true,
      'comment' => 'Unique identifier',
      'inline_edit' => false,
    ),
    'name' => 
    array (
      'name' => 'name',
      'vname' => 'LBL_NAME',
      'type' => 'name',
      'link' => true,
      'dbType' => 'varchar',
      'len' => 255,
      'unified_search' => false,
      'full_text_search' => 
      array (
        'boost' => 3,
      ),
      'required' => false,
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'merge_filter' => 'disabled',
      'inline_edit' => true,
      'duplicate_merge_dom_value' => '0',
    ),
    'date_entered' => 
    array (
      'name' => 'date_entered',
      'vname' => 'LBL_DATE_ENTERED',
      'type' => 'datetime',
      'group' => 'created_by_name',
      'comment' => 'Date record created',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'date_modified' => 
    array (
      'name' => 'date_modified',
      'vname' => 'LBL_DATE_MODIFIED',
      'type' => 'datetime',
      'group' => 'modified_by_name',
      'comment' => 'Date record last modified',
      'enable_range_search' => true,
      'options' => 'date_range_search_dom',
      'inline_edit' => false,
    ),
    'modified_user_id' => 
    array (
      'name' => 'modified_user_id',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_MODIFIED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'group' => 'modified_by_name',
      'dbType' => 'id',
      'reportable' => true,
      'comment' => 'User who last modified record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'modified_by_name' => 
    array (
      'name' => 'modified_by_name',
      'vname' => 'LBL_MODIFIED_NAME',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'rname' => 'user_name',
      'table' => 'users',
      'id_name' => 'modified_user_id',
      'module' => 'Users',
      'link' => 'modified_user_link',
      'duplicate_merge' => 'disabled',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by' => 
    array (
      'name' => 'created_by',
      'rname' => 'user_name',
      'id_name' => 'modified_user_id',
      'vname' => 'LBL_CREATED',
      'type' => 'assigned_user_name',
      'table' => 'users',
      'isnull' => 'false',
      'dbType' => 'id',
      'group' => 'created_by_name',
      'comment' => 'User who created record',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'created_by_name' => 
    array (
      'name' => 'created_by_name',
      'vname' => 'LBL_CREATED',
      'type' => 'relate',
      'reportable' => false,
      'link' => 'created_by_link',
      'rname' => 'user_name',
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'created_by',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
      'importable' => 'false',
      'massupdate' => false,
      'inline_edit' => false,
    ),
    'description' => 
    array (
      'name' => 'description',
      'vname' => 'LBL_DESCRIPTION',
      'type' => 'text',
      'comment' => 'Full text of the note',
      'rows' => 6,
      'cols' => 80,
    ),
    'deleted' => 
    array (
      'name' => 'deleted',
      'vname' => 'LBL_DELETED',
      'type' => 'bool',
      'default' => '0',
      'reportable' => false,
      'comment' => 'Record deletion indicator',
    ),
    'created_by_link' => 
    array (
      'name' => 'created_by_link',
      'type' => 'link',
      'relationship' => 'bill_billables_created_by',
      'vname' => 'LBL_CREATED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'modified_user_link' => 
    array (
      'name' => 'modified_user_link',
      'type' => 'link',
      'relationship' => 'bill_billables_modified_user',
      'vname' => 'LBL_MODIFIED_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
    ),
    'assigned_user_id' => 
    array (
      'name' => 'assigned_user_id',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'vname' => 'LBL_ASSIGNED_TO_ID',
      'group' => 'assigned_user_name',
      'type' => 'relate',
      'table' => 'users',
      'module' => 'Users',
      'reportable' => true,
      'isnull' => 'false',
      'dbType' => 'id',
      'audited' => true,
      'comment' => 'User ID assigned to record',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_name' => 
    array (
      'name' => 'assigned_user_name',
      'link' => 'assigned_user_link',
      'vname' => 'LBL_ASSIGNED_TO_NAME',
      'rname' => 'user_name',
      'type' => 'relate',
      'reportable' => false,
      'source' => 'non-db',
      'table' => 'users',
      'id_name' => 'assigned_user_id',
      'module' => 'Users',
      'duplicate_merge' => 'disabled',
    ),
    'assigned_user_link' => 
    array (
      'name' => 'assigned_user_link',
      'type' => 'link',
      'relationship' => 'bill_billables_assigned_user',
      'vname' => 'LBL_ASSIGNED_TO_USER',
      'link_type' => 'one',
      'module' => 'Users',
      'bean_name' => 'User',
      'source' => 'non-db',
      'duplicate_merge' => 'enabled',
      'rname' => 'user_name',
      'id_name' => 'assigned_user_id',
      'table' => 'users',
    ),
    'SecurityGroups' => 
    array (
      'name' => 'SecurityGroups',
      'type' => 'link',
      'relationship' => 'securitygroups_bill_billables',
      'module' => 'SecurityGroups',
      'bean_name' => 'SecurityGroup',
      'source' => 'non-db',
      'vname' => 'LBL_SECURITYGROUPS',
    ),
    'price_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'price',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'price_c',
      'vname' => 'LBL_PRICE',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'bill_Billablesprice_c',
      'custom_module' => 'bill_Billables',
    ),
    'hours_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Hours',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'hours_c',
      'vname' => 'LBL_HOURS',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '5',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'bill_Billableshours_c',
      'custom_module' => 'bill_Billables',
    ),
    'tot_est_time_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Estimated Time',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'tot_est_time_c',
      'vname' => 'LBL_TOT_EST_TIME',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '2',
      'id' => 'bill_Billablestot_est_time_c',
      'custom_module' => 'bill_Billables',
    ),
    'cuo_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'CUO',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'cuo_c',
      'vname' => 'LBL_CUO',
      'type' => 'enum',
      'massupdate' => '1',
      'default' => '142',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => true,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'CUO_list',
      'studio' => 'visible',
      'dependency' => false,
      'id' => 'bill_Billablescuo_c',
      'custom_module' => 'bill_Billables',
    ),
    'tasks_bill_billables_1' => 
    array (
      'name' => 'tasks_bill_billables_1',
      'type' => 'link',
      'relationship' => 'tasks_bill_billables_1',
      'source' => 'non-db',
      'module' => 'Tasks',
      'bean_name' => 'Task',
      'vname' => 'LBL_TASKS_BILL_BILLABLES_1_FROM_TASKS_TITLE',
      'id_name' => 'tasks_bill_billables_1tasks_ida',
    ),
    'tasks_bill_billables_1_name' => 
    array (
      'name' => 'tasks_bill_billables_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_TASKS_BILL_BILLABLES_1_FROM_TASKS_TITLE',
      'save' => true,
      'id_name' => 'tasks_bill_billables_1tasks_ida',
      'link' => 'tasks_bill_billables_1',
      'table' => 'tasks',
      'module' => 'Tasks',
      'rname' => 'name',
    ),
    'tasks_bill_billables_1tasks_ida' => 
    array (
      'name' => 'tasks_bill_billables_1tasks_ida',
      'type' => 'link',
      'relationship' => 'tasks_bill_billables_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_TASKS_BILL_BILLABLES_1_FROM_BILL_BILLABLES_TITLE',
    ),
    'projecttask_bill_billables_1' => 
    array (
      'name' => 'projecttask_bill_billables_1',
      'type' => 'link',
      'relationship' => 'projecttask_bill_billables_1',
      'source' => 'non-db',
      'module' => 'ProjectTask',
      'bean_name' => 'ProjectTask',
      'vname' => 'LBL_PROJECTTASK_BILL_BILLABLES_1_FROM_PROJECTTASK_TITLE',
      'id_name' => 'projecttask_bill_billables_1projecttask_ida',
    ),
    'projecttask_bill_billables_1_name' => 
    array (
      'name' => 'projecttask_bill_billables_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_PROJECTTASK_BILL_BILLABLES_1_FROM_PROJECTTASK_TITLE',
      'save' => true,
      'id_name' => 'projecttask_bill_billables_1projecttask_ida',
      'link' => 'projecttask_bill_billables_1',
      'table' => 'project_task',
      'module' => 'ProjectTask',
      'rname' => 'name',
    ),
    'projecttask_bill_billables_1projecttask_ida' => 
    array (
      'name' => 'projecttask_bill_billables_1projecttask_ida',
      'type' => 'link',
      'relationship' => 'projecttask_bill_billables_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_PROJECTTASK_BILL_BILLABLES_1_FROM_BILL_BILLABLES_TITLE',
    ),
    'status_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Status',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'status_c',
      'vname' => 'LBL_STATUS',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'bill_Billablesstatus_c',
      'custom_module' => 'bill_Billables',
    ),
    'doc_quantity_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Doc. Quantity',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'doc_quantity_c',
      'vname' => 'LBL_DOC_QUANTITY',
      'type' => 'int',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'enable_range_search' => false,
      'disable_num_format' => '',
      'min' => false,
      'max' => false,
      'id' => 'bill_Billablesdoc_quantity_c',
      'custom_module' => 'bill_Billables',
    ),
    'bill_date_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Bill Date',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'bill_date_c',
      'vname' => 'LBL_BILL_DATE',
      'type' => 'datetimecombo',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'enable_range_search' => false,
      'dbType' => 'datetime',
      'display_default' => 'now&12:00pm',
      'id' => 'bill_Billablesbill_date_c',
      'custom_module' => 'bill_Billables',
    ),
    'aos_quotes_bill_billables_1' => 
    array (
      'name' => 'aos_quotes_bill_billables_1',
      'type' => 'link',
      'relationship' => 'aos_quotes_bill_billables_1',
      'source' => 'non-db',
      'module' => 'AOS_Quotes',
      'bean_name' => 'AOS_Quotes',
      'vname' => 'LBL_AOS_QUOTES_BILL_BILLABLES_1_FROM_AOS_QUOTES_TITLE',
      'id_name' => 'aos_quotes_bill_billables_1aos_quotes_ida',
    ),
    'aos_quotes_bill_billables_1_name' => 
    array (
      'name' => 'aos_quotes_bill_billables_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_AOS_QUOTES_BILL_BILLABLES_1_FROM_AOS_QUOTES_TITLE',
      'save' => true,
      'id_name' => 'aos_quotes_bill_billables_1aos_quotes_ida',
      'link' => 'aos_quotes_bill_billables_1',
      'table' => 'aos_quotes',
      'module' => 'AOS_Quotes',
      'rname' => 'name',
    ),
    'aos_quotes_bill_billables_1aos_quotes_ida' => 
    array (
      'name' => 'aos_quotes_bill_billables_1aos_quotes_ida',
      'type' => 'link',
      'relationship' => 'aos_quotes_bill_billables_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_AOS_QUOTES_BILL_BILLABLES_1_FROM_BILL_BILLABLES_TITLE',
    ),
    'bill_status_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Bill Status',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'bill_status_c',
      'vname' => 'LBL_BILL_STATUS',
      'type' => 'dynamicenum',
      'massupdate' => '1',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => 100,
      'size' => '20',
      'options' => 'bill_status_list',
      'studio' => 'visible',
      'dbType' => 'enum',
      'parentenum' => '',
      'id' => 'bill_Billablesbill_status_c',
      'custom_module' => 'bill_Billables',
    ),
    'product_id_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'product id',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'product_id_c',
      'vname' => 'LBL_PRODUCT_ID',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'bill_Billablesproduct_id_c',
      'custom_module' => 'bill_Billables',
    ),
    'quantity_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Quantity',
      'required' => true,
      'source' => 'custom_fields',
      'name' => 'quantity_c',
      'vname' => 'LBL_QUANTITY',
      'type' => 'decimal',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '18',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => '0',
      'id' => 'bill_Billablesquantity_c',
      'custom_module' => 'bill_Billables',
    ),
    'billami_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'BillaMi',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'billami_c',
      'vname' => 'LBL_BILLAMI',
      'type' => 'text',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'false',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'studio' => 'visible',
      'rows' => '4',
      'cols' => '20',
      'id' => 'bill_Billablesbillami_c',
      'custom_module' => 'bill_Billables',
    ),
    'part_number_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'part number',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'part_number_c',
      'vname' => 'LBL_PART_NUMBER',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'bill_Billablespart_number_c',
      'custom_module' => 'bill_Billables',
    ),
    'b_date_c' => 
    array (
      'inline_edit' => '1',
      'options' => 'date_range_search_dom',
      'labelValue' => 'Date',
      'enable_range_search' => '1',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'b_date_c',
      'vname' => 'LBL_B_DATE',
      'type' => 'date',
      'massupdate' => '1',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'size' => '20',
      'display_default' => 'now',
      'id' => 'bill_Billablesb_date_c',
      'custom_module' => 'bill_Billables',
    ),
    'aos_products_bill_billables_1' => 
    array (
      'name' => 'aos_products_bill_billables_1',
      'type' => 'link',
      'relationship' => 'aos_products_bill_billables_1',
      'source' => 'non-db',
      'module' => 'AOS_Products',
      'bean_name' => 'AOS_Products',
      'vname' => 'LBL_AOS_PRODUCTS_BILL_BILLABLES_1_FROM_AOS_PRODUCTS_TITLE',
      'id_name' => 'aos_products_bill_billables_1aos_products_ida',
    ),
    'aos_products_bill_billables_1_name' => 
    array (
      'name' => 'aos_products_bill_billables_1_name',
      'type' => 'relate',
      'source' => 'non-db',
      'vname' => 'LBL_AOS_PRODUCTS_BILL_BILLABLES_1_FROM_AOS_PRODUCTS_TITLE',
      'save' => true,
      'id_name' => 'aos_products_bill_billables_1aos_products_ida',
      'link' => 'aos_products_bill_billables_1',
      'table' => 'aos_products',
      'module' => 'AOS_Products',
      'rname' => 'name',
    ),
    'aos_products_bill_billables_1aos_products_ida' => 
    array (
      'name' => 'aos_products_bill_billables_1aos_products_ida',
      'type' => 'link',
      'relationship' => 'aos_products_bill_billables_1',
      'source' => 'non-db',
      'reportable' => false,
      'side' => 'right',
      'vname' => 'LBL_AOS_PRODUCTS_BILL_BILLABLES_1_FROM_BILL_BILLABLES_TITLE',
    ),
    'parent_type' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Parent Type',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'parent_type',
      'vname' => 'LBL_PARENT_TYPE',
      'type' => 'varchar',
      'massupdate' => '0',
      'default' => 'AOS_Quotes',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '255',
      'size' => '20',
      'id' => 'bill_Billablesparent_type',
      'custom_module' => 'bill_Billables',
    ),
    'cost_c' => 
    array (
      'inline_edit' => '1',
      'labelValue' => 'Cost',
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'cost_c',
      'vname' => 'LBL_COST',
      'type' => 'currency',
      'massupdate' => '0',
      'default' => '',
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '26',
      'size' => '20',
      'enable_range_search' => false,
      'precision' => 6,
      'id' => 'bill_Billablescost_c',
      'custom_module' => 'bill_Billables',
    ),
    'currency_id' => 
    array (
      'inline_edit' => 1,
      'required' => false,
      'source' => 'custom_fields',
      'name' => 'currency_id',
      'vname' => 'LBL_CURRENCY',
      'type' => 'currency_id',
      'massupdate' => '0',
      'default' => NULL,
      'no_default' => false,
      'comments' => '',
      'help' => '',
      'importable' => 'true',
      'duplicate_merge' => 'disabled',
      'duplicate_merge_dom_value' => '0',
      'audited' => false,
      'reportable' => true,
      'unified_search' => false,
      'merge_filter' => 'disabled',
      'len' => '36',
      'size' => '20',
      'dbType' => 'id',
      'studio' => 'visible',
      'function' => 
      array (
        'name' => 'getCurrencyDropDown',
        'returns' => 'html',
      ),
      'id' => 'bill_Billablescurrency_id',
      'custom_module' => 'bill_Billables',
    ),
  ),
  'relationships' => 
  array (
    'bill_billables_modified_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'bill_Billables',
      'rhs_table' => 'bill_billables',
      'rhs_key' => 'modified_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'bill_billables_created_by' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'bill_Billables',
      'rhs_table' => 'bill_billables',
      'rhs_key' => 'created_by',
      'relationship_type' => 'one-to-many',
    ),
    'bill_billables_assigned_user' => 
    array (
      'lhs_module' => 'Users',
      'lhs_table' => 'users',
      'lhs_key' => 'id',
      'rhs_module' => 'bill_Billables',
      'rhs_table' => 'bill_billables',
      'rhs_key' => 'assigned_user_id',
      'relationship_type' => 'one-to-many',
    ),
    'securitygroups_bill_billables' => 
    array (
      'lhs_module' => 'SecurityGroups',
      'lhs_table' => 'securitygroups',
      'lhs_key' => 'id',
      'rhs_module' => 'bill_Billables',
      'rhs_table' => 'bill_billables',
      'rhs_key' => 'id',
      'relationship_type' => 'many-to-many',
      'join_table' => 'securitygroups_records',
      'join_key_lhs' => 'securitygroup_id',
      'join_key_rhs' => 'record_id',
      'relationship_role_column' => 'module',
      'relationship_role_column_value' => 'bill_Billables',
    ),
  ),
  'optimistic_locking' => true,
  'unified_search' => true,
  'indices' => 
  array (
    'id' => 
    array (
      'name' => 'bill_billablespk',
      'type' => 'primary',
      'fields' => 
      array (
        0 => 'id',
      ),
    ),
  ),
  'templates' => 
  array (
    'security_groups' => 'security_groups',
    'assignable' => 'assignable',
    'basic' => 'basic',
  ),
  'custom_fields' => true,
);